import "./globals.css";

import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import type { Metadata, Viewport } from "next";

import { CrispChat } from "@/scripts/crisp-chat";
import { GoogleAnalytics } from "@/scripts/google-analytics";
import { MicrosoftClarity } from "@/scripts/microsoft-clarity";

import { epilogue, poppins } from "./fonts";

export const viewport: Viewport = {
  themeColor: "black",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: true,
};

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL as string),
  title: {
    default: "Sheetfy | Transforme planilhas em API REST em Segundos",
    template: "%s | Sheetfy",
  },
  description:
    "Crie APIs REST profissionais a partir de planilhas. Sem código, sem servidores. Documentação automática, endpoints seguros e pronto em segundos.",
  keywords: [
    "excel para api",
    "csv para api rest",
    "criar api sem código",
    "planilha para api",
    "api generator",
    "excel to rest api",
    "spreadsheet api",
    "no-code api",
    "backend instantâneo",
    "api a partir de dados",
    "airtable alternative",
    "google sheet into an api",
    "planilha google api fácil",
    "planilha google banco de dados",
    "planilha http api",
    "planilha multiusuário api",
    "planilha para api",
    "planilha para app",
    "planilha para json",
    "planilha para mobile app",
    "planilha sem backend",
    "planilha tempo real api",
    "planilhas como backend",
    "planilhas em api",
    "planilia api",
    "backend sem codar",
    "banco via planilha",
    "banco de dados usando planilhas",
    "banco de dados excel",
    "backendless sheets",
    "backend via excel",
    "backend simples para landing page",
    "bot telegram planilha",
    "bot usando google sheets",
    "bot whatsapp planilha",
    "centralized spreadsheet api",
    "como integrar com sheets",
    "chatbot spreadsheet",
    "como automatizar usando sheets",
    "conectar google sheet api",
    "conexão google sheet",
    "criar api google sheet",
    "criar api rápido planilha",
    "criar micro api sheets",
    "crud planilha",
    "crud spreadsheet",
    "csv to api automatic",
    "database from spreadsheet",
    "database instantâneo com sheets",
    "excel automation",
    "excel como backend",
    "excel como database",
    "excel em api",
    "excel etl",
    "excel json api",
    "excel online to api",
    "excel para api",
    "excel para json automatico",
    "excel power automate api",
    "excel rest api",
    "excel rest api easy",
    "excel sheet api",
    "excel to json api",
    "excel usando api",
    "excel webhook",
    "excel workbook apis",
    "export api to spreadsheet",
    "sheets para front-end",
    "sheets para react",
    "sheets realtime api",
    "sheets to api",
    "sheets to website api",
    "sheets webhook",
    "sheetson",
    "sheetyfy",
    "sincronizar api com planilha",
    "spreadsheet api builder",
    "spreadsheet backend",
    "spreadsheet endpoints",
    "spreadsheet into api",
    "spreadsheet microservice",
    "spreadsheet rest api",
    "spreadsheet rest endpoint",
    "spreadsheet sync api",
    "spreadsheet to api",
    "supabase sheet alternative",
    "tabela compartilhada api",
    "tabela em api",
    "api com excel",
    "api for google sheets alternative",
    "api generator spreadsheet",
    "api para dashboards",
    "api para grafana via planilha",
    "api para metabase via planilha",
    "api para múltiplos usuários via planilha",
    "api para powerbi via sheets",
    "api prototyping spreadsheet",
    "api sem programação",
    "api sem servidor",
    "planilha google api",
    "planilha e api",
    "planilha como data source",
    "planilha como banco de dados",
    "planilha como api",
    "planilha api alternativa",
    "planila api",
    "pipedream sheets automation",
    "pipedream google sheet api",
    "pipedream excel api",
    "office365 excel api",
    "nocodeapi sheets",
    "nocode spreadsheet automation",
    "nocode database sheets",
    "nocode backend sheet",
    "nocode api builder",
    "n8n spreadsheet webhook",
    "n8n spreadsheet",
    "n8n sheets conector",
    "n8n sheets api",
    "n8n sheet integration",
    "n8n google sheet triggers",
    "n8n google sheet api",
    "n8n excel automation",
    "n8n db via sheets",
    "n8n database sheets",
    "n8n connector sheets",
    "n8n com planilhas",
    "n8n api no backend",
    "mock api spreadsheet",
    "make.com google sheets",
    "make spreadsheet automation",
    "make sheets api",
    "make excel integration",
    "make db with sheets",
    "make backend spreadsheet",
    "lowcode spreadsheet tool",
    "lowcode sheet backend",
    "import excel to api",
    "http api spreadsheet",
    "sheet api google",
    "gsheets webhook",
    "gsheets to api",
    "gsheet db",
    "gsheet database",
    "gsheet backend",
    "gsheet automation",
    "gsheet api",
    "google spreadsheet automation",
    "google shets api",
    "google sheets rest api",
    "google sheets integration api",
    "google sheets api automatic",
    "google sheet sync api",
    "google sheet into an api",
    "api simples para projeto",
    "api via planilha",
    "api via sheets",
    "automate n8n sheets",
    "automação de planilhas",
    "automação sheet bot api",
    "backend nocode",
    "backend rápido para protótipo",
    "backend rápido sem servidor",
    "export api to spreadsheet",
    "firebase sheets",
    "formulários para planilhas api",
    "gerar endpoints automaticamente",
    "google forms to api",
    "google sheat api",
    "google sheet api builder",
    "google sheet api no code",
    "google sheet bot",
    "google sheet connector",
    "preciso de api sem backend",
    "publish spreadsheet as api",
    "quero expor uma planilha como api",
    "restful api nocode",
    "shared spreadsheet database",
    "shedfy",
    "sheet api generator",
    "sheet api google",
    "sheet api tool",
    "sheet as database",
    "sheet best",
    "sheet data ingestion",
    "sheet etl",
    "sheet2api",
    "sheet realtime database",
    "sheetdb",
    "sheetfy",
    "sheets api",
    "sheets backend alternative",
    "sheets get post put delete",
    "sheets json api",
    "transform sheets in api",
    "transformar planilha em api",
    "transformar spreadsheet em api",
    "turn your google sheet into an api",
    "usar planilha como backend react",
    "webhook planilha",
    "zapier create api from sheets",
    "zapier excel integration",
    "zapier google spreadsheet",
    "zapier new api sheets",
    "zapier sheets api",
    "zapier webhook to sheet",
    "alternative to sheetdb",
    "sheety.co",
    "sheetbest.com",
    "sheety",
    "sheetbest",
    "sheetson",
    "apispreadsheets",
  ],
  authors: [{ name: "Sheetfy" }],
  creator: "Sheetfy",
  icons: {
    icon: "/icons/logo-light.png",
    apple: "/icons/apple-touch-icon.png",
  },
  openGraph: {
    type: "website",
    url: process.env.NEXT_PUBLIC_APP_URL as string,
    siteName: "Sheetfy",
    title: "Sheetfy | Transforme planilhas em API's REST em Segundos",
    description:
      "Crie API's REST profissionais a partir de planilhas. Sem código, sem deploy, com documentação automática.",
    images: [
      {
        url: "/images/og-image.png",
        width: 1200,
        height: 630,
        alt: "Sheetfy - Planilhas para API REST",
      },
    ],
    locale: "pt_BR",
  },
  twitter: {
    card: "summary_large_image",
    title: "Sheetfy | Transforme planilhas em API's REST em Segundos",
    description:
      "Crie API's REST profissionais a partir de planilhas. Sem código, sem deploy, com documentação automática.",
    images: ["/images/twitter-card.png"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-br"
      className={`${poppins.variable} ${epilogue.variable} scroll-smooth antialiased`}
    >
      <body>
        {children}
        {process.env.NODE_ENV === "production" && (
          <>
            <SpeedInsights />
            <Analytics />
            <CrispChat />
            <GoogleAnalytics />
            <MicrosoftClarity />
          </>
        )}
      </body>
    </html>
  );
}
